### PR TITLE
Simplify stripping "v" from version

### PR DESCRIPTION
**Pull request by szepeviktor**
Suggested by shellcheck https://github.com/koalaman/shellcheck/wiki/SC2001

Please consider introducing shellcheck in CI https://github.com/koalaman/shellcheck/wiki/TravisCI

### CODE REVIEW

**Comment by helen** [comment]
Thanks @szepeviktor, I'll get this merged. Would you like to open a separate issue for the Shellcheck suggestion, just so we can track that? I think it's a good idea, although perhaps in this case we should run the CI using GH Actions :)

**Comment by szepeviktor** [comment]
Done in #29

**Comment by szepeviktor** [comment]
@jeffpaul Is there anything to do here?

**Comment by jeffpaul** [comment]
@szepeviktor nope, just making sure to note you as assigned on the PR so we don't forget to credit you in the eventual release... thanks!

**Pull request merged**
